agentServicePubKey: "0x788b3863773214f0791d7be9714e6c3445518592590bebf8119833462c023b75"
workspaces:
  - name: Freemont
    description: Freemont
    streams:
      - name: DSC 142
        description: DSC 142
        selectors:
          - name: illegalParkingDetection
            conditions:
              - event_type:illegalParking
        deployments:
          - name: Illegal Parking Detection
            description: Illegal Parking Detection
            engagement: Illegal Parking detection
            isActive: true
            triggers:
              - name: all-events
                conditions:
                  - "*"
            engagementRules: []
            deploymentId: dep-21e72017
        streamId: stream-f5213550
    workspaceId: "2198"
engagements:
  - name: Illegal Parking detection
    description: Illegal Parking Detection
    file: ./engagements/engagement.ts
    version: 1.0.0
    engagementId: eng-2f8b9517
agents:
  - name: Object Detection
    alias: objectDetection
    description: Object Detection Agent
    version: 1.0.0
    tasks:
      - name: Yolo
        alias: yolo
        file: ./agents/object-detection/tasks/yolo.ts
        parameters:
          properties:
            image:
              type: string
          required: []
          type: object
        returns:
          properties:
            totalDetections:
              type: number
            detections:
              type: array
            processingTime:
              type: number
          type: object
    agentId: agent-628677bd
  - name: Parking Violation Detector
    alias: parkingViolationDetector
    description: Parking Violation Detector
    version: 1.0.0
    tasks:
      - name: Detect
        alias: detect
        file: ./agents/parking-violation-detector/tasks/detect.ts
        parameters:
          properties:
            timestamp:
              type: number
            detections:
              type: array
            telemetry:
              type: object
          required: []
          type: object
        returns:
          properties:
            value:
              type: array
          type: object
    agentId: agent-b89132b6
cubbies:
  - name: syncMission
    description: Synchronized drone mission data and violation records
    dataTypes:
      - json
      - search
    queries:
      - name: syncMission
        file: ./queries/syncMission.ts
        parameters:
          properties:
            missionId:
              type: string
            mode:
              type: string
            startTime:
              type: number
            endTime:
              type: number
            page:
              type: number
            pageSize:
              type: number
            afterTimestamp:
              type: number
            n:
              type: number
          required:
            - missionId
          type: object
        returns:
          properties:
            success:
              type: boolean
            data:
              type: object
          type: object
    cubbyId: 53d8630e-b8ab-4382-9973-5396dea72a80
agentServiceId: "2620"
